const cases = {
  ibm:{eyebrow:'IBM · San Jose · May—August 2026',title:'Making complex systems feel dependable.',role:'Product Manager Intern',time:'May 2026—August 2026',summary:'On IBM’s Content Cortex team, shipped product work for an agentic file management platform: accessibility criteria for 5+ edge cases, Playwright QA that surfaced 3+ RAG-agent defects, and customer-facing decks that translated backend architecture for sales.',work:'Content Cortex sits at the intersection of accessibility, quality, and AI infrastructure. The work was close to the questions that are easy to miss in a demo but matter deeply in a product: what happens at the edges, how do we know the agentic file manager works, and how does a complex system become legible to the people who depend on it?',principle:'Dependability is a product decision.',lesson:'The most advanced system still has to earn trust at the point where a person meets it.'},
  'mccombs-research':{eyebrow:'McCombs School of Business · Austin · 2025—present',title:'Transformers for retail personalization.',role:'Undergraduate Research Assistant',time:'June 2025—present',summary:'Decision science research using machine learning and optimization to improve transformer-based recommender systems for retail personalization.',work:'I defined evaluation requirements for retail recommender systems, comparing embedding vs. transformer models on accuracy and latency. I also analyzed self-attention architecture in existing research to inform design choices for a retail personalization model, collaborating with faculty.',principle:'Measure the model against the decision it is meant to support.',lesson:'A recommender only earns its place when evaluation is honest about accuracy, latency, and the choice a shopper actually faces.'},
  pocketworlds:{eyebrow:'PocketWorlds (YC S18) · Austin · 2025',title:'Automation should still feel human.',role:'Product Management Intern',time:'April—August 2025',summary:'Explored how AI can reduce repetitive work without making a customer experience feel cold, generic, or over-optimized.',work:'At PocketWorlds (YC S18), I worked on AI systems across support and internal workflows. The interesting part was never simply automating a step; it was deciding which steps deserved automation and which moments still needed human judgment, context, and care.',principle:'Efficiency should preserve empathy.',lesson:'The goal is not to remove the human from the loop. It is to give them a better loop.'},
  digimax:{eyebrow:'DigiMax · Barrington · 2023—2026',title:'Learning business by building one.',role:'Co-Founder',time:'January 2023—January 2026',summary:'Started a video-production agency and learned the unglamorous, valuable work behind turning an idea into a business.',work:'DigiMax meant finding a real problem, earning a first conversation, making a promise, and then delivering on it. It was a long running lesson in customer trust, iteration, and the difference between an idea that sounds good and work someone will pay for.',principle:'Ownership makes feedback real.',lesson:'When the outcome has your name on it, you learn to listen to the market without losing your point of view.'},
  resia:{eyebrow:'Resia · Austin · 2024—2025',title:'Start with the person, not the feature.',role:'Product Intern, AI Home Design',time:'August 2024—May 2025',summary:'Worked close to prospective customers to find where a better product could remove uncertainty from a complicated decision.',work:'The work began with conversations, not screens. Listening to how people described their homes, aspirations, and frustration made the product choices clearer. It was practice in translating a messy, emotional problem into useful direction for a team.',principle:'Attention is the first product skill.',lesson:'The right insight is often already there—if you stay close enough to hear it.'},
  'texas-momentum':{eyebrow:'Texas Momentum · Austin · 2025—2026',title:'Building the room you want to walk into.',role:'President',time:'January 2025—May 2026',summary:'Created ways for ambitious students, founders, operators, and investors to encounter one another and make something happen.',work:'Texas Momentum was about more than events. It was about creating an environment where a conversation can become a collaboration, and where people who may not otherwise meet have a reason to stay in the room.',principle:'Community is designed, then maintained.',lesson:'A strong room changes what people believe they can do next.'},
  'texas-pevc':{eyebrow:'Texas Private Equity & Venture Capital · 2025—present',title:'Building a campus investing community.',role:'Vice President of Logistics',time:'Spring 2025—present',summary:'Helping establish a new campus organization for students interested in private equity and venture capital.',work:'I forged partnerships with three school department heads to build credibility for the organization, helping grow it from zero to more than 100 interested members. I also lead a four-person team focused on word-of-mouth growth and campus awareness, bringing in more than 60 members.',principle:'Community grows through trust and momentum.',lesson:'The first few credible relationships make the next hundred conversations possible.'},
  'peer-advisor':{eyebrow:'Canfield Business Honors · 2025—present',title:'Helping students find their next step.',role:'Peer Advisor',time:'Fall 2025—present',summary:'Supporting Business Honors students with the academic and professional decisions directly in front of them.',work:'Alongside eight peer advisors and nine academic advisors, I help identify recurring student challenges and connect people with more than ten useful resources. I also mentor more than 20 students one-on-one around academic planning, professional development, and resume or recruiting questions.',principle:'Good guidance makes the next step feel possible.',lesson:'The best support is specific enough to be useful and human enough to be remembered.'},
  'texas-rise':{eyebrow:'Texas RISE · 2026—present',title:'Giving early ideas a first chance.',role:'Mentor',time:'Spring 2026—present',summary:'Mentoring local high school students as they turn an early idea into a first venture.',work:'I volunteer with Texas high schools, teaching entrepreneurship across eight-plus lessons and reaching more than ten students. The work is practical: help students form a startup idea, conduct market research, and present their business at a pitch-night competition.',principle:'Entrepreneurship becomes real when someone tries it.',lesson:'An early lesson can turn curiosity into the confidence to make something.'}
};
const key = new URLSearchParams(location.search).get('case') || 'ibm';
const item = cases[key] || cases.ibm;
document.title = `${item.role} — Preyansh Jain`;
for (const id of ['eyebrow','title','role','time','summary','work','principle','lesson']) document.querySelector(`#${id}`).textContent = item[id];
